language: node_js
node_js : 
  - node
services:
 - postgresql

before_install:
 - psql -c 'create database automart_test_db' -U postgres
install:
  - npm install
cache:
  directories:
    - "node_modules"
before_script:
  - npm run create_test_tables
script:
  - npm run test
after_success: 
  - npm run coveralls